import sys

print(f'working again')

sys.exit(1)